# Generated by Django 5.2.6 on 2025-10-02 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentes', '0001_initial'),
        ('automoveis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], default='analise', max_length=15, verbose_name='Status')),
                ('parecer_agente', models.TextField(blank=True, verbose_name='Parecer do Agente')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação/Reprovação')),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='automoveis.automovel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Aluguel',
                'verbose_name_plural': 'Pedidos de Aluguel',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('pedido', models.OneToOneField(limit_choices_to={'status': 'aprovado'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pedidos.pedido')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('banco_credor', models.ForeignKey(blank=True, help_text='Banco que concedeu o crédito, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.banco')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
