# Generated by Django 5.2.6 on 2025-10-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('empresa', 'Empresa')], max_length=10, verbose_name='Tipo')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('agente', models.OneToOneField(limit_choices_to={'tipo': 'banco'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agentes.agente')),
                ('codigo_bancario', models.CharField(max_length=10, unique=True, verbose_name='Código Bancário')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('agente', models.OneToOneField(limit_choices_to={'tipo': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agentes.agente')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
        ),
    ]
