# Generated by Django 5.2.6 on 2025-10-02 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Formato AAA1234 ou AAA1B34', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='A placa deve estar no formato AAA1234 ou AAA1B34 (padrão Mercosul).', regex='^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$')], verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Proprietário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'perfis'), ('model', 'perfil')), models.Q(('app_label', 'agentes'), ('model', 'agente')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Proprietário')),
            ],
            options={
                'verbose_name': 'Automóvel',
                'verbose_name_plural': 'Automóveis',
                'ordering': ['marca', 'modelo'],
            },
        ),
    ]
