# Generated by Django 5.2.6 on 2025-09-19 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('rg', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9.\\-A-Za-z]+$')], verbose_name='RG')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$')], verbose_name='CPF')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('profissao', models.CharField(blank=True, max_length=80, verbose_name='Profissão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empregador', models.CharField(max_length=120, verbose_name='Entidade Empregadora')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (R$)')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Rendimento',
                'verbose_name_plural': 'Rendimentos',
            },
        ),
    ]
